service:
  name: behavior recognition
  port: 5000
  tags: 
    - interface:gRPC
    - platform:mmaction2
    - algorithm:SlowFast
  weights_info: ./weights_info.yml

consul:
  ip: 10.10.10.2
  port: 8500